using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DFWFreeways.Models
{
    public partial class AerialGalleryList
    {


        public static List<AerialGalleryItem> spur366_pre_klyde_warren_images()
        {

            return new List<AerialGalleryItem>() {
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0156.JPG","20090623_aerial_0156-700.jpg", "20090623_aerial_0156-1700.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking west",
                    "Woodall Rodgers Freeway",
                    "Looking west.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. Museum Tower was built along the freeway." )),
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0159.JPG","20090623_aerial_0159-700.jpg", "20090623_aerial_0159-1700.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking west",
                    "Woodall Rodgers Freeway",
                    "Looking west.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. Museum Tower was built along the freeway." )),
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0162.JPG","20090623_aerial_0162-1050.jpg", "20090623_aerial_0162-2560.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking southwest",
                    "Woodall Rodgers Freeway",
                    "Looking southwest.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. Museum Tower was built along the freeway." )),
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0164.JPG","20090623_aerial_0164-1050.jpg", "20090623_aerial_0164-2560.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking southwest",
                    "Woodall Rodgers Freeway",
                    "Looking southwest.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. Museum Tower was built along the freeway." )),
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0169.JPG","20090623_aerial_0169-1050.jpg", "20090623_aerial_0169-2560.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking west",
                    "Woodall Rodgers Freeway",
                    "Looking west.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. Museum Tower was built along the freeway." )),
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0170.JPG","20090623_aerial_0170-1050.jpg", "20090623_aerial_0170-2560.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking west",
                    "Woodall Rodgers Freeway",
                    "Looking west.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. Museum Tower was built along the freeway." )),
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0172.JPG","20090623_aerial_0172-1050.jpg", "20090623_aerial_0172-2560.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking west",
                    "Woodall Rodgers Freeway",
                    "Looking west.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. Museum Tower was built along the freeway." )),
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0174.JPG","20090623_aerial_0174-1050.jpg", "20090623_aerial_0174-2560.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking west",
                    "Woodall Rodgers Freeway",
                    "Looking west.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. Museum Tower was built along the freeway." )),
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0177.JPG","20090623_aerial_0177-1050.jpg", "20090623_aerial_0177-2560.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking west",
                    "Woodall Rodgers Freeway",
                    "Looking west.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. Museum Tower was built along the freeway." )),
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0178.JPG","20090623_aerial_0178-1050.jpg", "20090623_aerial_0178-2560.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking southwest",
                    "Woodall Rodgers Freeway",
                    "Looking southwest.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. Museum Tower was built along the freeway." )),
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0181.JPG","20090623_aerial_0181-1050.jpg", "20090623_aerial_0181-2560.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking southwest",
                    "Woodall Rodgers Freeway",
                    "Looking southwest.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. Museum Tower was built along the freeway." )),
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0185.JPG","20090623_aerial_0185-1050.jpg", "20090623_aerial_0185-2560.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking west",
                    "Woodall Rodgers Freeway",
                    "Looking west.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. Museum Tower was built along the freeway." )),
                new AerialGalleryItem(new DateTime(2009,6,23),"20090623_aerial_0188.jpg", "20090623_aerial_0188-700.jpg","20090623_aerial_0188-1700.jpg", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking southwest",
                    "Woodall Rodgers Freeway",
                    "Looking southwest.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section." )),
                new AerialGalleryItem(new DateTime(2005,5,30),"","2a_sp366_looking_e_2005-05-30_ADJ_900.jpg", "2a_sp366_looking_e_2005-05-30_ADJ_2592x1554.png", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking northeast",
                    "Woodall Rodgers Freeway",
                    "Looking northeast.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. New development occurred along the freeway." )),
                new AerialGalleryItem(new DateTime(2005,5,30),"","3a_sp366_looking_e_2005-05-30_ADJ_900.jpg", "3a_sp366_looking_e_2005-05-30_ADJ_2499x1691.png", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking northeast",
                    "Woodall Rodgers Freeway",
                    "Looking northeast.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. New development occurred along the freeway." )),
                new AerialGalleryItem(new DateTime(2005,5,30),"","7a_sp366_looking_e_2005-05-30_ADJ_900.jpg", "7a_sp366_looking_e_2005-05-30_ADJ_1848x1508.png", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking northeast",
                    "Woodall Rodgers Freeway",
                    "Looking northeast.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. New development occurred along the freeway." )),
                new AerialGalleryItem(new DateTime(2005,5,30),"","8a_sp366_looking_e_2005-05-30_ADJ_900.jpg", "8a_sp366_looking_e_2005-05-30_ADJ_2406x1790.png", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking east",
                    "Woodall Rodgers Freeway",
                    "Looking east.",
                    new AerialStatus ("2015", "Modified", "Klyde Warren Park was built over the trenched freeway section. New development occurred along the freeway." )),
                new AerialGalleryItem(new DateTime(2005,5,30),"","5a_us75_looking_n_at_woodall_rogers_2005-05-30_ADJ_900.jpg", "5a_us75_looking_n_at_woodall_rogers_2005-05-30_ADJ_2695x1778.png", "aerial", 
                    "Woodall Rodgers Freeway at US 75",
                    "Woodall Rodgers Freeway at US 75, looking north",
                    "Woodall Rodgers Freeway",
                    "Interchange at US 75, looking north along US 75."),
                new AerialGalleryItem(new DateTime(2005,5,30),"","6a_spur366_looking_e_at_central_2005-05-30_900.jpg", "6a_spur366_looking_e_at_central_2005-05-30_2373x1601.png", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking northeast",
                    "Woodall Rodgers Freeway",
                    "Looking northeast."),
                new AerialGalleryItem(new DateTime(2005,5,30),"","8a_spur366_looking_sw_at_central_2005-05-30_ADJ_900.jpg", "8a_spur366_looking_sw_at_central_2005-05-30_ADJ_2669x1692.png", "aerial", 
                    "Woodall Rodgers Freeway",
                    "Woodall Rodgers Freeway, looking southwest",
                    "Woodall Rodgers Freeway",
                    "Looking southwest.",
                    new AerialStatus ("2015", "Partially obsolete", "Klyde Warren Park was built over the trenched freeway section. New development occurred along the freeway." ))

            
            };
        }
    }
}